### ISSUE TITLE
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str()

### ISSUE THREAD

**Issue by therefromhere** [edoburu/sphinxcontrib-django#24]
This is a little way off for now (Django 4.0 is scheduled for ~December 2022), but just a heads up on this warning:

```
sphinxcontrib_django/docstrings.py:145: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().

  help_text = strip_tags(force_text(field.help_text))
```

**Comment by therefromhere** [comment]
eg as seen in dj-stripe docs builds: https://travis-ci.org/github/dj-stripe/dj-stripe/jobs/673267022

**Comment by ErikKalkoken** [comment]
Since Django 4 is now out, this have become a more severe issue. Would be amazing if the related PR could be released.

**Comment by timoludwig** [comment]
@ErikKalkoken Since this repository is apparently no longer maintained, I added support for Django 4 to my fork [over a year ago](https://github.com/timoludwig/sphinxcontrib-django2/commit/66703432c8b5704b5bcbeca13a3fc93fa93e19fc):

- GitHub: [timoludwig/sphinxcontrib-django2](https://github.com/timoludwig/sphinxcontrib-django2)
- PyPi: [sphinxcontrib-django2](https://pypi.org/project/sphinxcontrib-django2/)
